# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

TOOL_NAME := af_xdp_ping_reply
USER_TARGETS := af_xdp_ping_reply
XDP_TARGETS  := af_xdp_kern
#TEST_FILE := tests/test-xdp-loader.sh
#MAN_PAGE := xdp-loader.8

USER_LIBS := -lpthread

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk


