# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

TOOL_NAME := af_xdp_tx
USER_TARGETS := af_xdp_tx_user
# XDP_TARGETS  := af_xdp_tx_kern
# TEST_FILE := tests/test-xdp-loader.sh
# MAN_PAGE := xdp-loader.8

USER_LIBS := -lpthread -Wno-unused-variable -Wno-unused-parameter

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk


